name: Fetch and Update Issues

on:
    schedule:
        - cron: "0 */2 * * *" # every 2 hours
    push:
        branches:
            - master

jobs:
    fetch-and-save-issues:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Compile TypeScript to JavaScript
              run: npm run compile:scripts

            - name: Fetch Issues from GitHub and Update Files
              env:
                  SFIGS_TOKEN: ${{ secrets.SFIGS_TOKEN }}
              run: npm run fetch-issues
